import { render, screen } from "@testing-library/react";
import ReleaseNotesPage from "@/app/(app)/release-notes/page";

describe("ReleaseNotesPage", () => {
  it("renders shipped release notes newest first", () => {
    render(<ReleaseNotesPage />);

    expect(screen.getByRole("heading", { name: "Release Notes" })).toBeInTheDocument();
    expect(screen.getByText("Programs & Registrations")).toBeInTheDocument();
    expect(screen.getAllByText("Programs, sessions, registrations, capacity, and waitlists now persist through Neon-backed workflows.").length).toBeGreaterThan(0);
    expect(screen.getByText("Program CRUD")).toBeInTheDocument();
    expect(screen.getByText("Session CRUD")).toBeInTheDocument();
    expect(screen.getByText("Registration persistence")).toBeInTheDocument();
    expect(screen.getByText("Capacity management")).toBeInTheDocument();
    expect(screen.getByText("Membership & Check-In Stabilization")).toBeInTheDocument();
    expect(screen.getAllByText("Membership and check-in workflows now provide clearer access decisions, safer duplicate prevention, and better persistence feedback.").length).toBeGreaterThan(0);
    expect(screen.getByText("Access-decision messaging")).toBeInTheDocument();
    expect(screen.getByText("Database query performance")).toBeInTheDocument();
    expect(screen.getByText("Duplicate overlapping active memberships are now rejected for the same owner, plan, and facility scope")).toBeInTheDocument();
    expect(screen.getByText("Memberships & Check-In Persistence")).toBeInTheDocument();
    expect(screen.getAllByText("Membership management and front-desk check-ins now persist through Neon with centralized access-rule evaluation.").length).toBeGreaterThan(0);
    expect(screen.getByText("Neon-backed membership management")).toBeInTheDocument();
    expect(screen.getByText("Persistent customer check-ins and check-outs")).toBeInTheDocument();
    expect(screen.getByText("Centralized access-rule evaluation")).toBeInTheDocument();
    expect(screen.getByText("Sitemap & Robots Configuration")).toBeInTheDocument();
    expect(screen.getAllByText("Public sitemap, crawler rules, and production canonical URLs now separate indexable Cairn pages from private application routes.").length).toBeGreaterThan(0);
    expect(screen.getByText("Public XML sitemap")).toBeInTheDocument();
    expect(screen.getByText("Search-engine crawler rules")).toBeInTheDocument();
    expect(screen.getByText("Canonical metadata for public Cairn pages")).toBeInTheDocument();
    expect(screen.getByText("Customer Operations Stabilization")).toBeInTheDocument();
    expect(screen.getAllByText("Customer and household workflows are stabilized with transactional writes, deterministic repository reads, and focused validation coverage.").length).toBeGreaterThan(0);
    expect(screen.getByText("Customer and household workflow reliability")).toBeInTheDocument();
    expect(screen.getByText("Customer delete and household mutation steps now run transactionally so related customer-household links cannot be partially updated")).toBeInTheDocument();
    expect(screen.getByText("Customer Administration & Data Quality")).toBeInTheDocument();
    expect(screen.getAllByText("Customer and household administration, data-source visibility, repository boundaries, and workflow coverage are finalized for v0.3.x.").length).toBeGreaterThan(0);
    expect(screen.getByText("Customer and household admin diagnostics")).toBeInTheDocument();
    expect(screen.getByText("Repository consistency")).toBeInTheDocument();
    expect(screen.getByText("Customer Experience Improvements")).toBeInTheDocument();
    expect(screen.getAllByText("Customer search, validation, duplicate warnings, and profile clarity are improved for Neon-backed records.").length).toBeGreaterThan(0);
    expect(screen.getByText("Neon-backed customer search")).toBeInTheDocument();
    expect(screen.getByText("Duplicate-customer warnings")).toBeInTheDocument();
    expect(screen.getByText("Household Persistence")).toBeInTheDocument();
    expect(screen.getAllByText("Household CRUD and customer-household relationships now persist through Neon.").length).toBeGreaterThan(0);
    expect(screen.getByText("Neon-backed household CRUD")).toBeInTheDocument();
    expect(screen.getByText("Persisted customer-household relationships")).toBeInTheDocument();
    expect(screen.getByText("Customer Persistence")).toBeInTheDocument();
    expect(screen.getByText("Customer CRUD")).toBeInTheDocument();
    expect(screen.getAllByText("Patch").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Minor").length).toBeGreaterThan(0);
    expect(screen.getByText("Real Data Foundation")).toBeInTheDocument();
    expect(screen.getAllByText("Initial real database foundation using Neon.").length).toBeGreaterThan(0);
    expect(screen.getByText("Neon database integration")).toBeInTheDocument();
    expect(screen.getByText("Pilot Readiness Release")).toBeInTheDocument();
    expect(screen.getByText("Stone Cairn branding")).toBeInTheDocument();
    expect(screen.getByText("Versioning and release process foundations")).toBeInTheDocument();
    expect(screen.getByText("Navigation organization")).toBeInTheDocument();
    expect(screen.getByText("Sidebar overflow")).toBeInTheDocument();
    expect(screen.getByText("Notification ordering issues")).toBeInTheDocument();
    expect(screen.getByText("Payment processing not connected")).toBeInTheDocument();
  });
});
